language: perl
perl:
    - 5.18

env:
    - VERSION="2.0" CPANM='cpanm --wget --mirror https://cpan.metacpan.org'

before_install:
    - sudo apt-get install -qq python-software-properties
    - echo "yes" | sudo add-apt-repository "ppa:chris-lea/zeromq"
    - sudo apt-get update -qq
    - perl -V

install:
    - sudo apt-get install -y curl mailutils build-essential git-core automake cpanminus rng-tools openjdk-7-jre-headless libtool pkg-config vim htop bind9 libzmq3-dev libffi6 libmoose-perl libmouse-perl libanyevent-perl liblwp-protocol-https-perl libxml2-dev libexpat-dev python-dev
    - cpanm --wget --mirror https://cpan.metacpan.org Regexp::Common
    - cpanm --wget --mirror https://cpan.metacpan.org Moo@1.007000
    - cpanm --wget --mirror https://cpan.metacpan.org Test::Simple@1.001014
    - cpanm --wget --mirror https://cpan.metacpan.org Mouse@2.4.1
    - cpanm --wget --mirror https://cpan.metacpan.org ZMQ::FFI@0.17
    - cpanm --wget --mirror https://cpan.metacpan.org Log::Log4perl@1.44
    - cpanm --wget --mirror https://cpan.metacpan.org Test::Exception@0.32
    - cpanm --wget --mirror https://cpan.metacpan.org MaxMind::DB::Reader@0.050005
    - cpanm --wget --mirror https://cpan.metacpan.org GeoIP2@0.040005
    - cpanm --wget --mirror https://cpan.metacpan.org Hijk@0.19
    - cpanm https://github.com/csirtgadgets/p5-cif-sdk/archive/master.tar.gz
    - cpanm https://github.com/kraih/mojo/archive/v5.82.tar.gz
    - cpanm http://cpan.metacpan.org/authors/id/D/DR/DRTECH/Search-Elasticsearch-1.19.tar.gz
    - sudo rm -f /dev/random
    - sudo mknod -m 0666 /dev/random c 1 9
    - echo HRNGDEVICE=/dev/urandom | sudo tee /etc/default/rng-tools
    - sudo /etc/init.d/rng-tools restart

before_script:
    - bash autogen.sh

script:
    - ./configure && make
    - time make deps NOTESTS=-n
    - CI_BUILD=1 make test

notifications:
    email:
        on_success: never
        on_failure: always
branches:
    only:
        - master
        - staging
